In [2]:
import numpy as np

Write a NumPy program to compute the multiplication of two given matrices.


In [3]:
mat1=[[1,2,3],[4,5,6],[7,8,9]]
mat2=[[10,10,10],[10,10,15],[1,1,10]]
multi_matr=np.dot(mat1,mat2)
multi_matr

array([[ 33,  33,  70],
       [ 96,  96, 175],
       [159, 159, 280]])

Write a NumPy program to compute the outer product of two given vectors.


In [13]:
matrix1 = np.array([[1,2, 3], [1,4, 3]])
matrix2 = np.array([[1,2,3]])
print(matrix1)
print(matrix2,'\n')
 
result = np.inner(matrix1, matrix2)
print(result)

[[1 2 3]
 [1 4 3]]
[[1 2 3]] 

[[14]
 [18]]


Write a NumPy program to compute the cross-product of two given vectors.


In [5]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]

print(p)
print(q)

result1 = np.cross(p, q)
result2 = np.cross(q, p)

print("Cross product of the said two vectors (p, q):")
print(result1)
print("Cross product of the said two vectors (q, p):")
print(result2) 

[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Cross product of the said two vectors (p, q):
[ 2 -3]
Cross product of the said two vectors (q, p):
[-2  3]


Write a NumPy program to compute the determinant of a given square array.


In [6]:
from numpy import linalg
matrix=np.array([[1,0,1],[1,2,3],[4,5,6]])
print(np.linalg.det(matrix))

-6.0


Write a NumPy program to compute the eigenvalues and eigenvectors of a given square array.


In [8]:
m = np.array([[1, 2], 
              [2, 3]]) 
  
print(m) 
  
w, v = np.linalg.eig(m) 
  
print(w,'\n') 
print(v)

[[1 2]
 [2 3]]
[-0.23606798  4.23606798] 

[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


Write a NumPy program to compute the inverse of a given matrix.


In [9]:
arr = np.array([[1, 2], [5, 6]]) 
inverse_array = np.linalg.inv(arr) 
print("Inverse array is ") 
print(inverse_array) 

Inverse array is 
[[-1.5   0.5 ]
 [ 1.25 -0.25]]


Write a NumPy program to compute the sum of the diagonal elements of a given array.


In [10]:
n_array = np.array([[55, 25, 15], 
                    [30, 44, 2], 
                    [11, 45, 77]]) 
  
print("Numpy Matrix is:") 
print(n_array) 
  
trace = np.trace(n_array) 
  
print("\nTrace of given 3X3 matrix:") 
print(trace)

Numpy Matrix is:
[[55 25 15]
 [30 44  2]
 [11 45 77]]

Trace of given 3X3 matrix:
176
